/*
 * This source file was generated by the Gradle 'init' task
 *
 * fizzbuzz
 *      solve for fizzbuzz
 *      count to 100
 *      but if divisible by 3, say "fizz"; if divisible by 5, "buzz", if 3 and 5, "fizzbuzz",
 *
 * for example
 *      1   -> 1            ✅
 *      3   -> fizz        ✅
 *      5   -> buzz        ✅
 *     15   -> fizzbuzz
 *
 * tdd
 *      red: write failing test
 *      green: get it to pass, quickly,
 *      refactor: clean up to definition of done
 * definition of done:
 *      all tests pass?
 *      reveals intent?
 *      no duplication?
 *      fewest elements?
 *
 */
package org.example;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class FizzbuzzTest {
    private Fizzbuzz f;

    @BeforeEach void setup() {
        f = new Fizzbuzz();
    }

    @Test void one_should_1() {
        final String result = f.fizzbuzz(1);
        assertEquals("1", result);
    }

    @Test void two_should_2() {
        assertEquals("2", f.fizzbuzz(2));
    }

    @Test void three_should_fizz() {
        assertEquals("fizz", f.fizzbuzz(3));
    }

    @Test void five_should_buzz() {
        assertEquals("buzz", f.fizzbuzz(5));
    }

    @Test void fifteen_should_fizzbuzz() {
        assertEquals("fizzbuzz", f.fizzbuzz(15));
    }
}
