/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public static void main(String[] args) {
        System.out.println(new App().fizzbuzz(1));
    }

    public String fizzbuzz(int n) {
        return String.valueOf(n);
    }
}
