/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class Fizzbuzz {
    public static void main(String[] args) {
        System.out.println(new Fizzbuzz().fizzbuzz(1));
    }

    public String fizzbuzz(int n) {
        //  if I knew how I'd write a local lambda divisibleBy (m)
        // but, wait, can't have named lambdas :)
        // const divisibleBy (m) => m%n==0

//        void divisibleBy(int m) {
//
//        }
        final boolean by3 = n % 3 == 0;
        final boolean by5 = n % 5 == 0;

        if (by3 && by5) return "fizzbuzz";

        if (by5) return "buzz";

        if (by3) return "fizz";

        return String.valueOf(n);
    }
}
